---
plugin: azure.azcollection.azure_rm

# Restrict discovery to the Terraform-created resource group
include_vm_resource_groups:
  - rg-terraform-demo

# Use environment variables set in GitHub Actions workflow
auth_source: env

# Only target Linux VMs (skip Windows/admin VMs)
include_vm_filters:
  - os_type: Linux

# Create Ansible groups dynamically from tags and location
keyed_groups:
  - key: tags.role
    prefix: role
  - key: location
    prefix: azure

# Always prefer the VM's public IP for SSH
hostnames:
  - public_ip

# Map public IP into ansible_host
compose:
  ansible_host: public_ip

# Inject SSH username from workflow environment (defaults to azureuser)
vars:
  ansible_user: "{{ lookup('env', 'TF_VAR_admin_username') | default('azureuser') }}"
