plugin: azure_rm
include_vm_resource_groups:
  - rg-terraform-demo
auth_source: auto
keyed_groups:
  - key: tags.role
    prefix: role
  - key: location
    prefix: azure
hostnames:
  - public_ip
compose:
  ansible_host: public_ip

