# Inventory for Ansible using Azure Resource Manager plugin
plugin: azure.azcollection.azure_rm

# Limit discovery to the Terraform-created resource group
include_vm_resource_groups:
  - rg-terraform-demo

# Use environment variables from GitHub Actions workflow for authentication
auth_source: env

# Only target Linux VMs (skip Windows/admin VMs)
include_vm_filters:
  - os_type: Linux

# Dynamically create groups based on VM tags and location
keyed_groups:
  - key: tags.role
    prefix: role
  - key: location
    prefix: azure

# Prefer the VM's public IP for SSH connections
hostnames:
  - public_ip

# Map public IP into ansible_host
compose:
  ansible_host: public_ip

# Default SSH username from environment variable, fallback to 'azureuser'
vars:
  ansible_user: "{{ lookup('env', 'TF_VAR_admin_username') | default('azureuser') }}"
  ansible_python_interpreter: /usr/bin/python3
