---
- name: Deploy containerised web application
  hosts: all
  become: yes
  vars:
    docker_compose_path: /home/azureuser/docker-compose.yml
    docker_compose_bin: /usr/local/bin/docker-compose
    health_check_retries: 10
    health_check_interval: 10

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - docker.io
          - curl
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64
        dest: "{{ docker_compose_bin }}"
        mode: '0755'
      # avoids re-download if file already exists
      force: no

    - name: Copy docker-compose file to VM
      copy:
        src: ../app/docker-compose.yml
        dest: "{{ docker_compose_path }}"
        owner: azureuser
        group: azureuser
        mode: '0644'

    - name: Run Docker Compose
      command: "{{ docker_compose_bin }} up -d"
      args:
        chdir: "{{ docker_compose_path | dirname }}"

    - name: Wait for healthy web container
      shell: |
        for i in $(seq 1 {{ health_check_retries }}); do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' web 2>/dev/null || echo "missing")
          if [ "$STATUS" = "healthy" ]; then exit 0; fi
          sleep {{ health_check_interval }}
        done
        exit 1
      register: web_health
      failed_when: web_health.rc != 0
      changed_when: false

    - name: Wait for healthy db container
      shell: |
        for i in $(seq 1 {{ health_check_retries }}); do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' db 2>/dev/null || echo "missing")
          if [ "$STATUS" = "healthy" ]; then exit 0; fi
          sleep {{ health_check_interval }}
        done
        exit 1
      register: db_health
      failed_when: db_health.rc != 0
      changed_when: false
