name: Azure Containerised Deployment

on:
  push:
    branches:
      - main

env:
  TF_VAR_resource_group_name: rg-terraform-demo
  TF_VAR_location: UK West
  TF_VAR_vm_size: Standard_B2s
  TF_VAR_admin_username: azureuser
  TF_VAR_ssh_public_key_path: id_rsa.pub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Generate terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          resource_group_name = "rg-terraform-demo"
          location            = "UK West"
          vm_size             = "Standard_B2s"
          admin_username      = "azureuser"
          ssh_public_key_path = "id_rsa.pub"
          EOF
        working-directory: ./terra

      - name: Terraform Init
        run: terraform init
        working-directory: ./terra

      - name: Create SSH public key file
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > id_rsa.pub
        working-directory: ./terra

      # Import existing resources
      - name: Terraform Import Existing Resources
        run: |
          terraform import azurerm_resource_group.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo
          terraform import azurerm_public_ip.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo/providers/Microsoft.Network/publicIPAddresses/publicip-terraform-demo
          terraform import azurerm_virtual_network.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo/providers/Microsoft.Network/virtualNetworks/vnet-terraform-demo
          terraform import azurerm_subnet.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo/providers/Microsoft.Network/virtualNetworks/vnet-terraform-demo/subnets/subnet-terraform-demo
          terraform import azurerm_network_interface.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo/providers/Microsoft.Network/networkInterfaces/nic-terraform-demo
          terraform import azurerm_linux_virtual_machine.main /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-demo/providers/Microsoft.Compute/virtualMachines/vm-terraform-demo
        working-directory: ./terra

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan.out
        working-directory: ./terra

      - name: Terraform Apply
        run: terraform apply tfplan.out
        working-directory: ./terra

      - name: Install Ansible and Azure dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip jq
          pip3 install 'ansible[azure]'
          ansible-galaxy collection install -r collections/requirements.yaml

      - name: Verify Azure inventory plugin
        run: ansible-doc -t inventory azure.azcollection.azure_rm

      - name: Export Azure credentials for Ansible
        id: azure-creds
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS }}' > azure.json
          echo "AZURE_CLIENT_ID=$(jq -r .clientId azure.json)" >> $GITHUB_ENV
          echo "AZURE_SECRET=$(jq -r .clientSecret azure.json)" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure.json)" >> $GITHUB_ENV
          echo "AZURE_TENANT=$(jq -r .tenantId azure.json)" >> $GITHUB_ENV

      # Debug: inventory
      - name: Debug Ansible inventory
        run: |
          echo ">>> Running ansible-inventory debug..."
          ansible-inventory -i ansible/azure_rm.yaml --inventory-plugin azure.azcollection.azure_rm --list -vvv
          echo ">>> Graph view:"
          ansible-inventory -i ansible/azure_rm.yaml --inventory-plugin azure.azcollection.azure_rm --graph

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/azure_rm.yaml --inventory-plugin azure.azcollection.azure_rm ansible/depplaybook.yaml -vvv

      - name: Validate container health
        run: |
          unhealthy=$(docker ps --filter "health=unhealthy" -q)
          if [ -n "$unhealthy" ]; then
            echo "Unhealthy containers detected:"
            docker inspect --format='{{.Name}}: {{json .State.Health}}' $unhealthy
            exit 1
          else
            echo "All containers are healthy."
          fi
